# Generated by Django 2.2.4 on 2019-08-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date_attend',
            new_name='date_added',
        ),
    ]
